name: Callint Workflow 2025 02

on:
  workflow_dispatch:

jobs:
  run-reusable-action:
    uses: SKeenan07/github-actions-test-callable/.github/workflows/root-action.yml@main
    with:
      var-1: "COMPUTER"
    # var-1: "DEVICE"

