name: Calling Workflow 2025 02

on:
  workflow_dispatch:
    inputs:
      var-1:
        description: 'Group type: COMPUTER or DEVICE'
        required: true
        type: choice
        options:
          - COMPUTER
          - DEVICE
        default: COMPUTER


jobs:
  check-out-callable:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: SKeenan07/github-actions-test-callable
        ref: main
    - name: Check contents
      run: ls -la
    - name: run reusable action
      uses: skeenan07/github-actions-test-callable/.github/workflows/root-action.yml@main
      with:
        var-1: ${{ github.event.inputs.var-1 }}

