name: The workflow to call other workflows

on:
  workflow_dispatch:

env:
  platform: "macos"
  # platform: "ios"
  var-2: "Hello"
  var-3: "World"

jobs:
  call-main-reusable-workflow:
    runs-on: macos-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4
        with: 
          repository: skeenan07/github-actions-test-callable
          ref: main
      - name: Call the main reusable workflow
        uses: skeenan07/github-actions-test-callable/action-main@main
        with:
          platform: ${{ env.platform }}
          var-2: ${{ env.var-2 }}
          var-3: ${{ env.var-3 }}