name: Scheduled Time Zone Test

on:
  schedule:
    - cron: '0 15 * * *' #STANDARD TIME
    - cron: '0 14 * * *' #DAYLIGHT SAVING TIME

jobs:
  check-time-zone:
    runs-on: ubuntu-latest
    steps: 
      - name: Check time zone
        run: | 
          CURRENT_HOUR=$(TZ="America/New_York" date +'%H')
          if [ "$CURRENT_HOUR" -ne 19 ]; then
            echo "Not 10 AM Eastern Time, skipping."
            exit 0  # Gracefully exit without error
          fi
      - name: Run the actual job
        run: echo "It's 10 AM Eastern! Running the job..."
        