name: Scheduled Time Zone Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *' #STANDARD TIME
    - cron: '0 14 * * *' #DAYLIGHT SAVING TIME

jobs:
  check-time-zone:
    runs-on: ubuntu-latest
    steps: 
      - name: Check time zone
        run: | 
          CURRENT_HOUR=$(TZ="America/New_York" date +'%H')
          if [ "$CURRENT_HOUR" -ne 19 ]; then
            echo "Not 10 AM Eastern Time, skipping."
            echo "correct-time=false" >> "$GITHUB_ENV"
          else
            echo "It's 10 AM Eastern Time!"
            echo "correct-time=true" >> "$GITHUB_ENV"
          fi
  
  check-out-code:
    runs-on: ubuntu-latest
    if: $correct-time == 'true'
    needs: check-time-zone
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: SKeenan07/github-actions-test-callable
          ref: main
      - name: Check contents
        run: ls -la

  
    
        