name: Scheduled Time Zone Test

on:

  workflow_dispatch:
    inputs:
      desired-hour:
        description: 'Desired Hour in 24-hour format (Eastern Time)'
        required: true

  schedule:
    - cron: '0 18 * * *' #STANDARD TIME
    - cron: '0 17 * * *' #DAYLIGHT SAVING TIME

env:
  DESIRED_HOUR: "13"

jobs:
  check-time-zone:
    runs-on: ubuntu-latest
    outputs:
      correct-time: ${{ steps.time-check.outputs.correct-time }}
    steps: 
      - name: Check time zone
        id: time-check
        run: | 
          CURRENT_HOUR=$(TZ="America/New_York" date +'%H')
          if [ "$CURRENT_HOUR" -ne "$DESIRED_HOUR" ]; then
            echo "Not 10 AM Eastern Time, skipping."
            echo "correct-time=false" >> $GITHUB_OUTPUT
          else
            echo "It's 10 AM Eastern Time!"
            echo "correct-time=true" >> $GITHUB_OUTPUT
          fi

  display-output:
    runs-on: ubuntu-latest
    needs: check-time-zone
    steps:
      - name: Display output
        run: echo "correct-time=${{ needs.check-time-zone.outputs.correct-time }}"
  
  check-out-code:
    runs-on: ubuntu-latest
    if: needs.check-time-zone.outputs.correct-time == 'true'
    needs: [check-time-zone, display-output]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: SKeenan07/github-actions-test-callable
          ref: main
      - name: Check contents
        run: ls -la

  
    
        